# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='This is my note', max_length=255),
        ),
    ]
